@api = http://localhost:5000/api/photos

### GET PHOTOS
GET {{api}}/get-photos

### ADD PHOTO
POST {{api}}/add-photo
Content-Type: application/json

{
    "label": "label of the image one",
    "url": "any url of the image"
}

### DELETE PHOTO
DELETE {{api}}/delete-photo/6251e28731124eeff02082d1